### ISSUE TITLE
Don't make me delete the example text in the form fields

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/henderson2016#10]
As a user, when I want to post a cool idea, I have to backspace away the example idea to put in my idea.

When I start typing in the text box, that example text should just disappear automatically. Ghost text! 👻

Fortunately this feature is built into modern browsers so we don't need to code it ourselves.
- [x] In post.html, in each of the `input` elements that the user can type text into, instead of setting the `value` (which is meant to be for what the user enters), set the `placeholder` instead.
- [x] test that the page looks and works correctly.

**Comment by Panda-skins** [comment]
I have done it and it is working now
